// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlqUZd0pJed8LupYZ3B0ejIGCqkPv8ERQ',
    appId: '1:495153818415:web:f21eaaac5c744a49d20fda',
    messagingSenderId: '495153818415',
    projectId: 'ms-potato',
    authDomain: 'ms-potato.firebaseapp.com',
    storageBucket: 'ms-potato.firebasestorage.app',
    measurementId: 'G-XLZ93H4J0P',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlqUZd0pJed8LupYZ3B0ejIGCqkPv8ERQ',
    appId: '1:495153818415:web:8017c12c456a63ccd20fda',
    messagingSenderId: '495153818415',
    projectId: 'ms-potato',
    authDomain: 'ms-potato.firebaseapp.com',
    storageBucket: 'ms-potato.firebasestorage.app',
    measurementId: 'G-ERF4P3WFBG',
  );
}
